spring:
  datasource:
    url: jdbc:mariadb://172.30.1.5:3306/board
    driver-class-name: org.mariadb.jdbc.Driver
    username: newuser
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: 1234

server:
  port: 8180
